config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get "/campaigns/dashboard", to: "campaigns#dashboard", as: "dashboard"

    resources :campaigns do
      resources :comments
      resources :donations
    end

  get "/:category/campaigns" => "campaigns#category", as: "category"

  get "/join" => "users#new", as: "signup"
  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  get "/profile" => "sessions#show", as: "profile"
  get "/profile/edit" => "users#edit", as: "edit_profile"
  get "/profile/password" => "users#password", as: "password_profile"

  get '/contact' => 'contact_us/contacts#new'
  get '/contact/thanks' => 'contact_us/contacts#thanks'

  resources :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate

  def index
    @campaigns = Campaign.where(["finalizado_en > ?", Date.today]).order(:cant_like)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1  style= "font-family: Fjalla One, sans-serif; font-size: 50px; color: #64A300;">Let's GoGo</h1>

<% if @campaigns.any? %>
  <div id="myCarousel" class="carousel slide" data-ride="carousel" style="width: 600px; float: center;">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <% if @campaigns[1] %>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      <% end %>
      <% if @campaigns[2] %>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      <% end %>
      <% if @campaigns[3] %>
        <li data-target="#myCarousel" data-slide-to="3"></li>
      <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="<%= @campaigns[0].image %>" height="400px" width="400px">
        <div class="carousel-caption">
          <div style="background-color: rgba(39, 55, 70, 0.7); border-radius: 25px;">
            <h3 style= "font-family: Fjalla One, sans-serif; padding-top: 5px"><%= link_to @campaigns[0].titulo, campaign_path(@campaigns[0]), {:style => 'color:  #64A300;'}%></h3>
            <p style= "font-family: Roboto Condensed, sans-serif; font-size: 15px"><%= @campaigns[0].category %> • Meta: Lps. <%= @campaigns[0].meta %> Recaudado: Lps. <%= cant_recuadada(@campaigns[0].donations) %></p>
          </div>
        </div>
      </div>

      <% if @campaigns[1] %>
      <div class="item">
        <img src="<%= @campaigns[1].image %>" height="400px" width="400px">
        <div class="carousel-caption">
          <div style="background-color: rgba(39, 55, 70, 0.7); border-radius: 25px;">
            <h3 style= "font-family: Fjalla One, sans-serif; padding-top: 5px"><%= link_to @campaigns[1].titulo, campaign_path(@campaigns[1]), {:style => 'color:  #64A300;'}%></h3>
            <p style= "font-family: Roboto Condensed, sans-serif; font-size: 15px"><%= @campaigns[1].category %> • Meta: Lps. <%= @campaigns[1].meta %> Recaudado: Lps. <%= cant_recuadada(@campaigns[1].donations) %></p>
          </div>
        </div>
      </div>
      <% end %>

      <% if @campaigns[2] %>
      <div class="item">
        <img src="<%= @campaigns[2].image %>" height="400px" width="400px">
        <div class="carousel-caption">
          <div style="background-color: rgba(39, 55, 70, 0.7); border-radius: 25px;">
            <h3 style= "font-family: Fjalla One, sans-serif; padding-top: 5px"><%= link_to @campaigns[2].titulo, campaign_path(@campaigns[2]), {:style => 'color:  #64A300;'}%></h3>
            <p style= "font-family: Roboto Condensed, sans-serif; font-size: 15px"><%= @campaigns[2].category %> • Meta: Lps. <%= @campaigns[2].meta %> Recaudado: Lps. <%= cant_recuadada(@campaigns[2].donations) %></p>
          </div>
        </div>
      </div>
      <% end %>

      <% if @campaigns[3] %>
      <div class="item">
        <img src="<%= @campaigns[3].image %>" height="400px" width="400px">
        <div class="carousel-caption">
          <div style="background-color: rgba(39, 55, 70, 0.7); border-radius: 25px;">
            <h3 style= "font-family: Fjalla One, sans-serif; padding-top: 5px"><%= link_to @campaigns[3].titulo, campaign_path(@campaigns[3]), {:style => 'color:  #64A300;'}%></h3>
            <p style= "font-family: Roboto Condensed, sans-serif; font-size: 15px"><%= @campaigns[3].category %> • Meta: Lps. <%= @campaigns[3].meta %> Recaudado: Lps. <%= cant_recuadada(@campaigns[3].donations) %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% end %>

<div style= "float: center; padding-right: 100px" >
  <%= link_to category_path("Salud") do %>
    <%= image_tag "salud.png", style: "heigth: 400px; width: 400px; padding-bottom: 10px; display:inline-block" %>
  <% end %>
  <%= link_to category_path("Educacion") do %>
    <%= image_tag "educacion.png", style: "heigth: 280px; width: 280px; padding-bottom: 10px; display:inline-block" %>
  <% end %>
  <%= link_to category_path("Recreacion") do %>
    <%= image_tag "recreacion.png", style: "heigth: 340px; width: 340px; padding-bottom: 10px; padding-left: 50px; display:inline-block" %>
  <% end %>
  <%= link_to category_path("Religion") do %>
    <%= image_tag "religion.png", style: "heigth: 300px; width: 300px; padding-bottom: 10px; padding-left: 10px; display:inline-block" %>
  <% end %>
  <%= link_to category_path("Viaje") do %>
    <%= image_tag "viaje.png", style: "heigth: 300px; width: 300px; padding-bottom: 10px; padding-left: 20px; display:inline-block" %>
  <% end %>
</div>