config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get "/campaigns/dashboard", to: "campaigns#dashboard", as: "dashboard"

    resources :campaigns do
      resources :comments
      resources :donations
    end

  get "/:category/campaigns" => "campaigns#category", as: "category"

  get "/join" => "users#new", as: "signup"
  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  get "/profile" => "sessions#show", as: "profile"
  get "/profile/edit" => "users#edit", as: "edit_profile"
  get "/profile/password" => "users#password", as: "password_profile"

  get '/contact' => 'contact_us/contacts#new'
  get '/contact/thanks' => 'contact_us/contacts#thanks'

  resources :users

end

app/controllers/contact_us/contacts_controller.rb
class ContactUs::ContactsController < ApplicationController
  skip_before_action :authenticate

  def create
    @contact = ContactUs::Contact.new(params[:contact_us_contact])

    if @contact.save
      redirect_to contact_thanks_path
    else
      flash[:error] = t('contact_us.notices.error')
      render_new_page
    end
  end

  def new
    @contact = ContactUs::Contact.new
    render_new_page
  end

  def thanks

  end

  protected

    def render_new_page
      case ContactUs.form_gem
      when 'formtastic'  then render 'new_formtastic'
      when 'simple_form' then render 'new_simple_form'
      else
        render 'new'
      end
    end

end

app/views/contact_us/contacts/new.html.erb
<h1 style="font-size: 30px; font-family: Anton, sans-serif; color: #64A300"><%= t('.contact_us')  %></h1>
<div style="width: 500px">
  <%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
    <% if ContactUs.require_name %>
      <div class='string required' id='contact_us_contact_name_input'>
        <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
        <%= f.text_field :name, class: "form-control" %>
        <% if f.object.errors[:name].present? %>
          <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
        <% end %>
      </div>
    <% end %>
    <div class='string required' id='contact_us_contact_email_input'>
      <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :email, class: "form-control" %>
      <% if f.object.errors[:email].present? %>
        <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
      <% end %>
    </div>
    <% if ContactUs.require_subject %>
      <div class='string required' id='contact_us_contact_subject_input'>
        <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
        <%= f.text_field :subject,class: "form-control" %>
        <% if f.object.errors[:subject].present? %>
          <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
        <% end %>
      </div>
    <% end %>
    <div class='text required' id='contact_us_contact_message_input'>
      <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_area :message, class: "form-control" %>
      <% if f.object.errors[:message].present? %>
        <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
      <% end %>
    </div>
    <div class='commit'>
      <%= f.submit :submit, :class => 'submit create', :title => t('.submit') %>
    </div>
  <% end %>
</div>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
<% end %>

app/views/contact_us/contacts/thanks.html.erb
<p style="font-size: 30px; font-family: Anton, sans-serif; color: #64A300" >
  Gracias!
</p>
<p style= "font-family: Roboto Condensed, sans-serif; font-size: 25px">
  Agradecemos sus comentarios y sugerencias!
</p>