config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get "/campaigns/dashboard", to: "campaigns#dashboard", as: "dashboard"

    resources :campaigns do
      resources :comments
      resources :donations
    end

  get "/:category/campaigns" => "campaigns#category", as: "category"

  get "/join" => "users#new", as: "signup"
  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  get "/profile" => "sessions#show", as: "profile"
  get "/profile/edit" => "users#edit", as: "edit_profile"
  get "/profile/password" => "users#password", as: "password_profile"

  get '/contact' => 'contact_us/contacts#new'
  get '/contact/thanks' => 'contact_us/contacts#thanks'

  resources :users

end

app/models/campaign.rb
class Campaign < ApplicationRecord
  scope :active, ->{where(["finalizado_en >= ?", Date.today])}

  def self.categories
    ["Salud", "Recreacion", "Religion", "Educacion", "Viaje"]
  end

  has_many :comments
  has_many :donations

  belongs_to :user

  validates :titulo, presence: true
  validates :resena, presence: true, length: {maximum: 140}
  validates :meta, presence: true, numericality: {greater_than: 0}
  validates :category, presence: true
  validate :date_is_before_six_months

  def date_is_before_six_months
    if self.finalizado_en.present? && (self.finalizado_en > (Date.today + 6.months))
      errors.add(:finalizado_en, 'No puede durar mas de 6 meses')
    end
  end

  before_create :default_image
  before_update :default_image

  before_create :default_date
  before_update :default_date

  protected

  def default_image
    if image == ""
      self.image='https://upload.wikimedia.org/wikipedia/commons/d/d1/Black_circle.png'
    end
  end

  def default_date
    if finalizado_en == nil
      self.finalizado_en = Date.today + 6.months
    end
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  skip_before_action :authenticate, only: [:index, :show, :category]

  def index
    @campaigns = Campaign.active.order(:created_at)
  end

  def show
    @campaign = Campaign.find(params[:id])
    @user = User.find_by(id: @campaign.user_id)
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id
    @campaign.cant_like = 0

    if @campaign.save
      UserNotifierMailer.campaign_create(current_user, @campaign).deliver
      redirect_to dashboard_path, notice: "Se agrego exitosamente."
    else
      render :new
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])

    if @campaign.update_attributes(campaign_params)
      if current_user.receive_email
        UserNotifierMailer.campaign_edit(current_user, @campaign).deliver
      end
      redirect_to campaign_path(@campaign),  notice: "Se edito con exito."
    else
      render :edit
    end
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy
    redirect_to campaigns_path,  notice: "Se borro con exito."
  end

  def category
    @campaigns = Campaign.where(["category like ?", params[:category]])
    @category = params[:category].to_s
  end

  def dashboard
    @campaigns = Campaign.where(["user_id = ?", current_user.id])
  end

  protected

  def campaign_params
    params.require(:campaign).permit!
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign_comments.html.erb
<% if campaign.comments.any? %>
	<div>
		<h2>Comments: </h2>
		<table border="2">
			<thead>
				<th>ID</th>
				<th>Nombre</th>
			</thead>
			<tbody>
				<%= render campaign.comments.order("created_at DESC") %>
			</tbody>
		</table>
	</div>
<% else %>
	<p><em>No hay categories.</em></p>
<% end %>

app/views/campaigns/_campaign_donations.html.erb
<% if donations.any? %>
	<div>
		<h2 style= "font-family: Fjalla One, sans-serif; font-size: 25px">Donations: </h2>
		<table class="table table-hover" style="width:500px">
			<thead>
				<th>Autor</th>
				<th>Monto Hecho</th>
        <th>Mensaje</th>
        <th>Fecha Creado</th>
        <th>

        </th>
			</thead>
			<tbody>
				<%= render donations %>
			</tbody>
		</table>
	</div>
<% else %>
	<p><em>No hay donations.</em></p>
<% end %>

app/views/campaigns/category.html.erb
<h1 style="font-size: 30px; font-family: Anton, sans-serif; color: #0064A3" >
	<% if @category == "Salud" %>
		Salud
	<% end %>
	<% if @category == "Educacion" %>
		Educacion
	<% end %>
	<% if @category == "Recreacion" %>
		Recreacion
	<% end %>
	<% if @category == "Religion" %>
		Religion
	<% end %>
	<% if @category == "Viaje" %>
		Viaje
	<% end %>
</h1>

<% if flash[:notice] %>
	<div>
		<%= flash[:notice] %>
	</div>
<% end %>

<div style="width: 600px; height: 180px; background: #64A300; border-radius: 25px; padding-bottom: 50px">
		<div style="float: left; align: top">
			<% if @category == "Salud" %>
		    <%= image_tag "salud.png", style: "heigth: 200px; width: 200px; padding-bottom: 10px; display:inline-block" %>
		  <% end %>
		  <% if @category == "Educacion" %>
		    <%= image_tag "educacion.png", style: "heigth: 165px; width: 165px; padding-top: 10px; padding-left: 5px; display:inline-block" %>
		  <% end %>
		  <% if @category == "Recreacion" %>
		    <%= image_tag "recreacion.png", style: "heigth: 165px; width: 165px; padding-top: 10px; padding-left: 5px; display:inline-block" %>
		  <% end %>
		  <% if @category == "Religion" %>
		    <%= image_tag "religion.png", style: "heigth: 170px; width: 170px; padding-left: 10px; padding-top: 10px; display:inline-block" %>
		  <% end %>
		  <% if @category == "Viaje" %>
		    <%= image_tag "viaje.png", style: "heigth: 165px; width: 165px; padding-left: 5px; padding-top: 10px; display:inline-block" %>
		  <% end %>
		</div>

			<% if @category == "Salud" %>
			<p style="padding-top:20px; font-family: Roboto Condensed, sans-serif; font-size: 20px; padding-right: 20px;">
				Buscar mantener un equilibrio en nuestro diario vivir deberia ser un objetivo constante en la vida de cada uno de nosotros. Cualquier camapaña que tenga como objetivo mejorar la salud de nuestros clientes es bienvenida en Let's GoGo.

			<% end %>
			<% if @category == "Educacion" %>
				<p style="padding-top:10px; font-family: Roboto Condensed, sans-serif; font-size: 17px; padding-right: 20px;">
					El saber es poder. En Let's Go Go motivamos a nuestros clientes a emprender un viaje buscando absorber la mayor cantidad de conocimientos y expandir sus barreras, para sobresalir en la sociedad como ningun otro. Un libro, una bibliografia de tu autor favorito incluso suscripciones para paginas que proveen tutoriales, crea tu campaña y crece junto a nosotros.
				</p>
			<% end %>
			<% if @category == "Recreacion" %>
				<p style="padding-top:20px; font-family: Roboto Condensed, sans-serif; font-size: 20px; padding-right: 20px;">
					Una nueva consola, un instrumento, un nuevo calzado para practicar tu deporte favorito, en Let's GoGo apoyamos a todos para obtener sus deseos. Porque siempre es bueno buscar relajar nuestra mente y engrandecer nuestros talentos.
				</p>
			<% end %>
			<% if @category == "Religion" %>
				<p style="padding-top:30px; font-family: Roboto Condensed, sans-serif; font-size: 20px; padding-right: 20px;">
					La espiritualidad de cada uno de nuestros clientes es importante, si deseas crear una campaña para cualquier religion y ayudar a tu comunidad este es el lugar perfecto para ti.
				</p>
			<% end %>
			<% if @category == "Viaje" %>
				<p style="padding-top:10px; font-family: Roboto Condensed, sans-serif; font-size: 20px; padding-right: 20px;">
					Deseas emprender al otro lado del mundo? o simplemente conocer la ciudad de al lado? En Lets GoGo puedes buscar la ayuda que necesitas, Los Alpes, el Everest o Copan Ruinas, conoce al mundo y asi mismo descubrete a ti mismo. Un universo lleno de maravillas te esta esperando. Ve y buscalo.
				</p>
			<% end %>
</div>

<table class="table table-hover" style="width:1000px">
	<thead>
		<tr>
			<th>Titulo</th>
			<th>Reseña</th>
			<th>Categoria</th>
			<th>Meta</th>
			<th>Monto Donado</th>
			<th>Creado En</th>
			<th>Usuario Creador</th>
		</tr>
	</thead>
	<tbody>
			<%- @campaigns.each do |f| %>
				<tr>
					<td><%= link_to f.titulo, campaign_path(f) %></td>
					<td><%= f.resena %></td>
					<td><%= f.category %></td>
					<td><%= f.meta %></td>
					<td>Lps. <%= cant_recuadada(f.donations) %></td>
					<td><%= format_date(f.created_at) %></td>
					<td><%= User.find(f.user_id).name %></td>
				</tr>
			<%- end %>
	</tbody>
</table>

app/views/campaigns/dashboard.html.erb
<h1 style="font-size: 30px; font-family: Anton, sans-serif; color: #64A300" >My Dashboard</h1>

<% if flash[:notice] %>
	<div>
		<%= flash[:notice] %>
	</div>
<% end %>

<table class="table table-hover" style="width:1000px">
	<thead>
		<tr>
			<th>Titulo</th>
			<th>Reseña</th>
			<th>Categoria</th>
			<th>Meta</th>
			<th>Monto Donado</th>
			<th>Creado En</th>
			<th>Usuario Creador</th>
		</tr>
	</thead>
	<tbody>
			<%- @campaigns.each do |f| %>
				<tr>
					<td><%= link_to f.titulo, campaign_path(f) %></td>
					<td><%= f.resena %></td>
					<td><%= f.category %></td>
					<td><%= f.meta %></td>
					<td> Lps. <%= cant_recuadada(f.donations) %></td>
					<td><%= format_date(f.created_at) %></td>
					<td><%= User.find(f.user_id).name %></td>
				</tr>
			<%- end %>
	</tbody>
</table>

app/views/campaigns/edit.html.erb
<h1 style="font-size: 30px; font-family: Anton, sans-serif; color: #64A300" >Edit Campaign</h1>
<p> <em> Ingrese los datos necesarios: </em> </p>

<% if @campaign.errors.any? %>
  <div>
    Por favor corrija los siguientes problemas:
    <ul>
      <% @campaign.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>


<div style="width: 500px">
  <%= form_for @campaign do |f| %>
    <p>
      <%= f.label :titulo, "Titulo", class: "input-group"%>
      <%= f.text_field :titulo, class: "form-control" %>
    </p>

    <p>
      <%= f.label :resena, "Resena", class: "input-group"  %>
      <%= f.text_field :resena, class: "form-control" %>
    </p>

    <p>
      <%= f.label :description , class: "input-group"%>
      <%= f.text_area :description, class: "form-control"%>
    </p>

    <p>
      <%= f.label :category , class: "input-group"%>
      <%= f.select :category, Campaign.categories, class: "form-control"%>
    </p>

    <p>
      <%= f.label :image, "Imagen", class: "input-group" %>
      <%= f.text_field :image, class: "form-control" %>
    </p>

    <p>
      <%= f.label :finalizado_en, "Finaliza en", class: "input-group" %>
      <%= f.date_field :finalizado_en, class: "form-control" %>
    </p>

    <p>
      <%= f.submit "Update", class:"btn btn-default btn-lg" %>
      <%= link_to "Cancelar", campaigns_path, class:"btn btn-default btn-lg" %>
      <% unless @campaign.donations.any? %>
        <%= link_to "Borrar", @campaign, method: :delete, data: {confirm: "Are you really sure?"}, class:"btn btn-default btn-lg" %>
      <% end %>
    </p>

  <% end %>

</div>

app/views/campaigns/index.html.erb
<h1 style="font-size: 30px; font-family: Anton, sans-serif; color: #64A300" >List of Campaigns</h1>

<% if flash[:notice] %>
	<div>
		<%= flash[:notice] %>
	</div>
<% end %>

<table class="table table-hover" style="width:1000px">
	<thead style="font-size: 18px; font-family: Fjalla One, sans-serif; color: #00263D">
		<tr>
			<th>Titulo</th>
			<th>Reseña</th>
			<th>Categoria</th>
			<th>Meta</th>
			<th>Monto Donado</th>
			<th>Creado En</th>
			<th>Usuario Creador</th>
		</tr>
	</thead>
	<tbody>
		<%- @campaigns.each do |f| %>
			<tr>
				<td><%= link_to f.titulo, campaign_path(f) %></td>
				<td><%= f.resena %></td>
				<td><%= link_to f.category, category_path(f.category) %></td>
				<td><%= f.meta %></td>
				<td>Lps. <%= cant_recuadada(f.donations) %></td>
				<td><%= format_date(f.created_at) %></td>
				<td><%= User.find(f.user_id).name %></td>
			</tr>
		<%- end %>
	</tbody>
</table>

app/views/campaigns/new.html.erb
<h1 style="font-size: 30px; font-family: Anton, sans-serif; color: #64A300" >New Campaign</h1>
<p> <em> Ingrese los datos necesarios: </em> </p>

<% if @campaign.errors.any? %>
  <div>
    Por favor corrija los siguientes problemas:
    <ul>
      <% @campaign.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div style="width: 500px">
  <%= form_for @campaign do |f| %>
    <p>
      <%= f.label :titulo, "Titulo", class: "input-group"%>
      <%= f.text_field :titulo, class: "form-control" %>
    </p>

    <p>
      <%= f.label :resena, "Resena", class: "input-group"  %>
      <%= f.text_field :resena, class: "form-control" %>
    </p>

    <p>
      <%= f.label :description , class: "input-group"%>
      <%= f.text_area :description, class: "form-control"%>
    </p>

    <p>
      <%= f.label :category , class: "input-group"%>
      <%= f.select :category, Campaign.categories, class: "dropdown"%>
    </p>

    <p>
      <%= f.label :meta, class: "input-group"%>
      <%= f.number_field :meta, class: "form-control"%>
    </p>

    <p>
      <%= f.label :image, "Imagen", class: "input-group" %>
      <%= f.text_field :image, class: "form-control" %>
    </p>

    <p>
      <%= f.label :finalizado_en, "Finaliza en", class: "input-group" %>
      <%= f.date_field :finalizado_en, class: "form-control" %>
    </p>

    <p>
      <%= f.submit "Crear", class:"btn btn-default btn-lg" %>
      <%= link_to "Cancelar", campaigns_path, class:"btn btn-default btn-lg" %>
    </p>

  <% end %>
</div>

app/views/campaigns/show.html.erb
<h1 style="font-size: 30px; font-family: Anton, sans-serif; color: #64A300" ><%=@campaign.titulo %></h1>
<% if flash[:notice] %>
  <div style="background: yellow">
    <%= flash[:notice] %>
  </div>
<% end %>

<div style= "float: right; padding-right: 200px" >
  <%= image_tag @campaign.image, style: "heigth: 400px; width: 400px; padding-bottom: 10px" %>


  <div class="progress" style="width: 400px;">
    <div class="progress-bar" role="progressbar" aria-valuenow= "<%=porciento_completado(@campaign) * 100 %>"
    aria-valuemin="0" aria-valuemax="100" style="width: <%=porciento_completado(@campaign) * 100 %>%">
      <%= porciento_completado(@campaign) * 100 %>% Completado
    </div>


  </div>

  <div style= "font-family: Roboto Condensed, sans-serif; font-size: 20px; border-radius: 25px; border: solid black 2px; ">
    <p>
      <%=@user.name %>
    </p>
    <p>
      <%=@user.ciudad %>, <%=@user.pais %>
    </p>
    <p>
      <%= mail_to @user.email, "Enviar correo" %>
    </p>
  </div>
</div>

<ul class="list-group" style= "font-family: Fjalla One, sans-serif; font-size: 25px">
	<li>
		Description:
		<light style= "font-family: Roboto Condensed, sans-serif"><%= @campaign.description %></light>
	</li>
  <li>
    Meta:
    <light style= "font-family: Roboto Condensed, sans-serif"><%= @campaign.meta %></light>
  </li>
  <li>
    Category:
    <light style= "font-family: Roboto Condensed, sans-serif"><%= link_to @campaign.category, category_path(@campaign.category) %></light>
  </li>
  <li>
    Cantidad de Likes:
    <light style= "font-family: Roboto Condensed, sans-serif"><%= @campaign.cant_like %></light>
  </li>
  <li>
    Fecha culminacion:
    <light style= "font-family: Roboto Condensed, sans-serif"><%= format_date(@campaign.finalizado_en) %></light>
  </li>
  <li>
    Fecha creacion:
    <light style= "font-family: Roboto Condensed, sans-serif"><%= format_date(@campaign.created_at)  %></light>
  </li>
</ul>

<p style= "font-family: Fjalla One, sans-serif; font-size: 25px">
  Comentarios
</p>

<% if @campaign.comments.any? %>
<table class="table table-hover" style="width:500px">
	<thead>
		<tr>
			<th>Autor</th>
			<th>Mensaje</th>
			<th>Fecha Creacion</th>
      <th>

      </th>
		</tr>
	</thead>
	<tbody>
			<%- @campaign.comments.each do |f| %>
				<tr>
					<td><%= f.autor %></td>
					<td><%= f.mensaje %></td>
					<td><%= format_date(f.created_at)  %></td>
          <% if current_user %>
              <% if current_user == User.find_by(name: f.autor) %>
					       <td><%= link_to "Borrar", campaign_comment_path(f.campaign, f), method: :delete, data: {confirm: "Estas Seguro?"} %></td>
              <% end %>
          <% end %>
				</tr>
			<%- end %>
	</tbody>
</table>
<% else %>
  <p><em>No hay comentarios.</em></p>
<% end %>

<%= render partial: "campaign_donations", locals: {donations: @campaign.donations.order("created_at DESC")} %>

<p style="display: inline-block"> <%= link_to "New Donation", new_campaign_donation_path(@campaign.id), class:"btn btn-default btn-lg" %> </p>

<p style="display: inline-block"> <%= link_to "New Comment", new_campaign_comment_path(@campaign.id), class:"btn btn-default btn-lg" %> </p>

<% if current_user %>
  <% if current_user.id == @campaign.user_id %>
    <p style="display: inline-block"> <%= link_to "Edit", edit_campaign_path, class:"btn btn-default btn-lg" %> </p>
  <% end %>
<% end %>