config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get "/campaigns/dashboard", to: "campaigns#dashboard", as: "dashboard"

    resources :campaigns do
      resources :comments
      resources :donations
    end

  get "/:category/campaigns" => "campaigns#category", as: "category"

  get "/join" => "users#new", as: "signup"
  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  get "/profile" => "sessions#show", as: "profile"
  get "/profile/edit" => "users#edit", as: "edit_profile"
  get "/profile/password" => "users#password", as: "password_profile"

  get '/contact' => 'contact_us/contacts#new'
  get '/contact/thanks' => 'contact_us/contacts#thanks'

  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Let's GoGo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-full" style="background: linear-gradient(#FFFFFF, #ECF0F1);">


  <!-- Navigation -->
    <nav class="navbar  navbar-full navbar-light" style="background-color: #00263D" role="navigation">
              <a class="navbar-brand" style="height: 30px; padding-left: 30px"><%=image_tag "logo.png", style: "height: 32px" %></a>
                <ul class="nav navbar-nav" style= "float: right">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li>
                        <%= link_to "Home", root_path, {:style => 'color: #64A300; font-size: 30px; font-family: Anton, sans-serif;'} %>
                    </li>
                    <li>
                        <%= link_to "Campaigns", campaigns_path, {:style => 'color: #64A300; font-size: 30px; font-family: Anton, sans-serif;'} %>
                    </li>
                    <% if current_user %>
                    <li>
                      <%= link_to "Start a Campaign", new_campaign_path, {:style => 'color: #64A300; font-size: 30px; font-family: Anton, sans-serif;'} %>
                    </li>

                    <li>
                      <%= link_to "My Dashboard", dashboard_path, {:style => 'color: #64A300; font-size: 30px; font-family: Anton, sans-serif;'} %>
                    </li>

                    <li>
                      <%= link_to "Profile", profile_path, {:style => 'color: #64A300; font-size: 30px; font-family: Anton, sans-serif;'} %>
                    </li>

                    <li>
                      <%= link_to "Log Out", logout_path, {data: {method: :delete}, :style => 'color: #64A300; font-size: 30px; font-family: Anton, sans-serif;'} %>
                    </li>
                    <% else%>
                    <li>
                      <%= link_to "Log In", login_path, {:style => 'color: #64A300; font-size: 30px; font-family: Anton, sans-serif;'} %>
                    </li>
                    <li>
                      <%= link_to "Sign Up", signup_path, {:style => 'color: #64A300; font-size: 30px; font-family: Anton, sans-serif;'} %>
                    </li>
                    <%end%>
                </ul>
    </nav>


  <div align= "center">
    <%= yield %>
  </div>


    <footer>
        <div class="container text-center">
            <p style= "font-family: Roboto Condensed, sans-serif; font-size: 25px"> Jonathan & Edgar, Experiencia de Usuario 2016</p>
        </div>
    </footer>
</body>
</html>